env:
  global:
  # PYPI_TOKEN
  # alias travis='docker run --rm -v $PWD:/repo -v ~/.travis:/travis ubergarm/travis-ci-cli'
  # travis login --pro --github-token <github token>
  # travis encrypt PYPI_TOKEN=<token> -r Sovetnikov/livelock --pro
  - secure: "G8R1A9EMfwxw/o9xOZir7VA3hNt0Y43fN8hdh21yld1qLcZX6pE9xq6VAWy1GyE/f+BPWwhbdBQp14T9fvt1OXywukPRblfMOMC5SpeKotmm3hcvrzezH/4kC9VplcPz3flT5pWCPIrePV6FFoPNIIbu3E8LjUaXM8XwtKzxJ7tpKcsQ/7iZtKlCPyS8xvS0Qsfg55LKV/X+Gc1R6Q5+WUYd6r1Td792s3jXh9BVKaDzddOhbqIsK5SuUoQSHBiUWVvaHugmV/I0bTaDXYVlYUhORH1bz+D84LAfLdZuxoM8D13I+vGSk6FsZTllxnoRaundBKCicd44UqxJavpJN6jGSYZJjDthAW0htlBwj5rwEa+IFfiRLWCD3kevfeIaM7wwjjZGYgCVGPAf6BE/SaCh7EFPSjqxfnXuX0di50IeFTFR6TMvpd6wM58E77M13Qf80PsPn1qVTWRI/M0M+GhfbIF/2qDJFwKwn1vd5gw46wFW7l/Pg2V+9kzD75yYmqJufeSBu6NtIy2OuyGW9D4WLAZ3zZ6GAnyzK82AENsGJ8lRsOVDvfdAb11jg2vaoTA/Ua0Hj86OAPJ2Yl+9VNlFEX4l199OCCZZDZncjQN+EOL1yMSu9eSjnS6dTTplmLybTuz2xSirBJzUohsXi3m13Why4URWw4mo08K91+I="
  # PYPI_TEST_TOKEN
  - secure: "ju3Ia4KUUfW12cjOBSqD0fmfNggeFosaNz5hxMkklwJYEV4czjXcyAfm5hvCJV+B0qhkbqGAEowRJCgBOdmok1CtCY9IiYatCw4ewR9RVavqRBYFLZxPSyJKvKHrjkDXsw9ON/BfGbgk1b/797GdF5IaSgjFA3CrSCfbUoRFwQKESKOF99+Dm+/8TU1rHka5H71tgPi7KbDLoPA8NIc0QlvWMTWiJLNJQbnUvE+wwBvMxCdGdve7uARg62RitEDUf6Y2f9epES6dhkaVjpNjqFY4JP5mEPV/J8M8B7A9KRN3NLoVUuH5fJcZR9ouOK/F1JI5A9c5L1Jd/nSJS93DBFuekiF1AuaAd3lroQ5XHqfodesOkuUkbg0BxZDwPkn8YgtxLcsxC13W0pMTwYtOUThOAKcLma4YExRUQzbRWYzQJG5Zt2kYTj+3CcGLmoO0UgcuOquXwYmfFZnwqQNJQjtsEE5SEL5hGkDWg0N7Eih+55I3NvtJ/tNUAdjmApgUvHnxfb+8YtW7cJua255WEGagZwueN8iGXc2NUuiS5yDMhXj6KnuNeiEDmlbWHUUjQqnDj9FF0rcr+Hj+F/PbgiJTobcsog6YQpM23en8AWzs6xd210OVTgvB6JBXES4cGe/Hht/Z/jiejk75LfIavccQsJaS4BHuDzWsjSKydCw="
  # DOCKER_PASSWORD
  - secure: "RPlsVfcOA+VgmBRB9WnBgnOFTdLZgv5EqFjq8qirU8ZRuRgQ6ia7MflVvlPNobwoPozYEC6Zw6bourM7DnrIVl9rcMJOS5rtm/HGdKOCd1Nf/uWphD0aYyq9f7UaWLSA2zVp/+DfajsaiCcFc4sslD23Z6gDdP/ji0KV28En0C8f1hi4Qc+FgPqXETmb946ZH+VTqFi8K8pEM19tZW4QDTFZvWHNIGi3A4Kkj9PVRTEFWDIl8rXeS4cEPLz4+cvg+FKPLSNrCoqn35aZq1M/NmsuZBm0PTLUXU1A4E3NqDgG5jbgkU8bCLRNFm6gGByhmaz09Bbq66dh8kmcJxhb7qEOKnliHJHv2pkAYHY9qqf8ub5NUg72/bT0KWzOjtA0/T4gOCi7f5rjgLBU/UzSoUzgoL/DM6W0Y6NNhOdS2btIPAYK7QaDLgAsmGaxQBfSRcpMi5Twi9vrSAHBo8rpYL5HWNUN95Tf4aaGWkDw0IzlJLi1yvQg1nBkFPDtYXf2jGydAp1S6Z2BoP7q3W4t3u2c3K1WUMsIxAQITJBsngl2nsQyi7Yr07EIIRd57wSVSxThk4C4ATQ+ck+aJcHPyXBO4JPHs8kUZ46pzeb/Tt5a3gCewbzKq21qRdzsGE8KOGauhAH4Nt7+009ZiO//DUOXoA9IEHMTUl3Ie84Tr3Q="
language: python
cache: pip
python:
- 3.7
install:
- pip install -e .
script:
- pytest
matrix:
  include:
  - python: 3.7
deploy:
  provider: pypi
  skip_existing: true
  on:
    branch: master
  user: "__token__"
#  true:
#    all_branches: true
  password: $PYPI_TOKEN
#  server: https://test.pypi.org/legacy/
#  password: $PYPI_TEST_TOKEN
after_success:
  - export VERSION=`python setup.py --version`
  - echo "$DOCKER_PASSWORD" | docker login -u "sovetnikov" --password-stdin
  - docker build -t sovetnikov/livelock:latest -t sovetnikov/livelock:$VERSION .
  - docker push sovetnikov/livelock:latest
  - docker push sovetnikov/livelock:$VERSION
